version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  gs-spring-boot-docker:
    image: springio/gs-spring-boot-docker
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
